server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_codingrecipe?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_codingrecipe
    password: 1111
  thymeleaf:
    cache: false

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect  # MySQL8Dialect로 변경
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: email-smtp.us-east-1.amazonaws.com
    port: 587
    username: AKIA3TD31SHQ4LUVZQEVL          # Access Key ID
    password: a8KzDAWQ6M5Il766832S2BTsLzt6D/gI03A+pIbH # Secret Access Key
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html

