server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://web-ide-rds.c3aeygqk6msc.us-east-1.rds.amazonaws.com:3306/codewave?serverTimezone=Asia/Seoul
    username: admin
    password: Codewave0130!
  thymeleaf:
    cache: false

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect  # MySQL8Dialect로 변경
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: hazardous0212@gmail.com
    password: xuia jmka shqj kxnr
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
app:
  auth:
    token-secret: ABCDSADSDADABCDSADSDADABCDSADSDADABCDSADSDADABCDSADSDADABCDSADSDAD
  cors:
    allowed-origins: http://localhost:3000, http://localhost:8080

springdoc:
  api-docs:
    path: /v3/api-docs  # OpenAPI 문서 경로
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 경로
